version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/crawler"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/indexer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
